export const paths = {
  login: '/login',
  loadingPage: '/loading-page',
  home: '/home',
  profile: '/profile',
  irregularities: '/irregularities',
  uploadCertificate: '/upload-certificate',
  verifyCertificate: '/verify-certificate',
  loadInformation: '/load-information',
  sendSuccess: '/send-success',
  uploadFailed: '/upload-failed',
  filterResults: '/filter-results',
  totalResults: '/total-results',
  deskList: '/desk-list',
  index: '',
};
